trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Electron'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build:prod'
    workingDir: 'Electron'
- task: Npm@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  env:
    GH_TOKEN: $(GH_TOKEN)
  inputs:
    command: 'custom'
    customCommand: 'run build:prod'
    workingDir: 'Electron'
